### ISSUE TITLE
Define metadata.yaml schema

### ISSUE THREAD

**Issue by trangdata** [EpistasisLab/pmlb#22]
Here's what I'm thinking for the metadata.yaml schema. We can set up CI to validate this schema (potentially with [jsonschema](https://python-jsonschema.readthedocs.io/en/stable/)?)

Then a README of summary statistics/csv files can be automatically generated (which will allow for easy querying such as [this](https://github.com/EpistasisLab/penn-ml-benchmarks/issues/3)). 

```
hashid: # required, hash id of the dataset
dataset: # required, dataset name
description: # required, dataset description
source: # required, link to the source from where dataset was retrieved
publication: # optional, study that generated the dataset
task: # required, classification or regression
columns: 
    [column_name]: # can be 'target'
        type:  # required, either continuous, nominal or ordinal
        description: # required, what the column measures/indicates, unit
        code: # optional, coding information, e.g., 'Control' = 0, 'Case' = 1
        transform: # optional, any transformation performed on the column, e.g., log scaled
```

**Comment by lacava** [comment]
thanks @trang1618 this looks good. a couple questions:

- what does `feature_specific` mean? could it just be called "features" or "feature_info" or something?
- could we make a template .yaml file and add it to the project? that would be a great thing to point to for contributions.

**Comment by trangdata** [comment]
Good point. I updated the schema. And yes, I can make an example .yaml file for one of the datasets.

**Comment by trangdata** [comment]
So I think we should use `column` instead of `feature` because we want to include 'target' in this field as well. Any thoughts?

**Comment by weixuanfu** [comment]
I think we should keep `features` and add `target` for target info only.

**Comment by trangdata** [comment]
> I think we should keep `features` and add `target` for target info only.

We certainly can have a different group for 'target', but it would have the exact same fields as the features, no?

**Comment by lacava** [comment]
I tend to agree with @weixuanfu. Even if they are the same, 'feature' and 'target' are specific supervised learning objects. 'column' is not and it's format specific, and we may at some point want to support data that is not in columns.

**Comment by trangdata** [comment]
Fair enough. How about this:
```
dataset: # required, dataset name
description: # required, dataset description
source: # required, link to the source from where dataset was retrieved
publication: # optional, study that generated the dataset (doi, pmid, pmcid, or url)
task: # required, classification or regression
target:
  type:
  description: # required, describe the endpoint/outcome (and unit if exists)
  code: # optional but recommended, coding information, e.g., 'Control' = 0, 'Case' = 1
features: # list of features in the dataset
  - name: # required, name of feature
    type: # required, either continuous, nominal or ordinal
    description: # optional but recommended, what the feature measures/indicates, unit
    code: # optional, coding information, e.g., 'Control = 0', 'Case' = 1
    transform: # optional, any transformation performed on the feature, e.g., log scaled
  - name:
    type:
    description:
    code:
    transform:
```
